"""
Agent Runner
Discovers, schedules, and executes agents from ~/.screenmind/agents/.
Supports two types:
  - .md (Markdown Agents) — Gemma-powered, no code needed
  - .py (Python Plugins) — full code, for developers
"""

import asyncio
import importlib.util
import logging
import os
import re
import sys
import threading
import time
import traceback
from collections import deque
from datetime import datetime
from pathlib import Path
from typing import Optional

from screenmind.config import settings

logger = logging.getLogger("screenmind.engine.agent_runner")


# ── Agent Log ────────────────────────────────────────────────────────
_agent_log = deque(maxlen=30)
_log_lock = threading.Lock()

# Approved Python plugins (user confirmed to run)
_approved_plugins = set()

# Persistent log file
_LOG_FILE = settings.data_path / "agents" / "run_log.json"


def _load_log():
    """Load persisted log from disk."""
    global _agent_log
    try:
        if _LOG_FILE.exists():
            import json
            data = json.loads(_LOG_FILE.read_text(encoding="utf-8"))
            _agent_log = deque(data[-30:], maxlen=30)
    except Exception:
        pass

_load_log()


def get_agent_log() -> list:
    """Return agent run log (newest first)."""
    with _log_lock:
        return list(reversed(_agent_log))


def _log_run(name: str, agent_type: str, status: str, output: str = "", error: str = "", duration: float = 0, output_dest: str = "local"):
    entry = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "name": name,
        "type": agent_type,
        "status": status,
        "output": output[:500],
        "error": error[:200],
        "duration": round(duration, 1),
    }
    with _log_lock:
        _agent_log.append(entry)
        # Persist to disk
        try:
            import json
            _LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
            _LOG_FILE.write_text(json.dumps(list(_agent_log), indent=2), encoding="utf-8")
        except Exception:
            pass

    if status != "ok" or not output:
        return

    # Parse comma-separated destinations: "local", "obsidian", "webhook", or combos
    dests = {d.strip().lower() for d in output_dest.split(",")}

    # Local file backup (always runs) — use slug for consistent path
    slug = name.lower().replace(" ", "-")
    _save_agent_output(slug, output)

    # Obsidian
    if "obsidian" in dests:
        _push_to_obsidian(name, output)

    # Webhook (Slack, Discord, custom HTTP endpoints)
    if "webhook" in dests:
        _push_to_webhook(name, output)


def _save_agent_output(name: str, output: str):
    """Save agent output to agents/output/{name}/{timestamp}.md for history."""
    try:
        out_dir = settings.data_path / "agents" / "output" / name
        out_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y-%m-%d_%H-%M")
        filepath = out_dir / f"{ts}.md"
        filepath.write_text(f"# {name} — {ts}\n\n{output}", encoding="utf-8")
    except Exception:
        pass


def _push_to_obsidian(name: str, output: str):
    """If Obsidian is enabled, write agent output to vault."""
    try:
        if not settings.obsidian_enabled or not settings.obsidian_vault_path:
            return
        vault = Path(settings.obsidian_vault_path)
        if not vault.is_dir():
            return

        # Write to {vault}/ScreenMind/Agents/{name}/{date}.md
        agent_dir = vault / "ScreenMind" / "Agents" / name
        agent_dir.mkdir(parents=True, exist_ok=True)

        date_str = datetime.now().strftime("%Y-%m-%d")
        filepath = agent_dir / f"{date_str}.md"

        content = f"# {name} — {date_str}\n\n"
        content += f"*Auto-generated by ScreenMind agent at {datetime.now().strftime('%H:%M')}*\n\n"
        content += "---\n\n"
        content += output.strip() + "\n\n"
        content += f"---\n\n#screenmind #agent #{name.lower().replace(' ', '-')}\n"

        filepath.write_text(content, encoding="utf-8")
        logger.info(f"Obsidian: Agent '{name}' output -> {filepath}")
    except Exception as e:
        logger.error(f"Obsidian: Agent push failed: {e}")


def _push_to_webhook(name: str, output: str):
    """Push agent output to configured webhook URL (Slack, Discord, etc.)."""
    try:
        if not settings.webhook_enabled or not settings.webhook_url:
            return

        import json
        import urllib.request

        url = settings.webhook_url
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Format payload — compatible with Slack/Discord incoming webhooks
        payload = {
            "text": f"*{name}* — {date_str}\n\n{output[:2000]}",
            "content": f"**{name}** — {date_str}\n\n{output[:2000]}",  # Discord
            "agent": name,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "source": "screenmind",
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url, data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        urllib.request.urlopen(req, timeout=10)
        logger.info(f"Webhook: Agent '{name}' output sent")
    except Exception as e:
        logger.error(f"Webhook: Agent push failed: {e}")


# ── Agent Discovery ──────────────────────────────────────────────────

def get_agents_dir() -> Path:
    """Get the agents directory, creating it if needed."""
    agents_dir = settings.data_path / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    return agents_dir


def _parse_md_frontmatter(filepath: Path) -> dict:
    """Parse YAML-like frontmatter from a markdown agent file."""
    text = filepath.read_text(encoding="utf-8")
    meta = {"name": filepath.stem, "type": "markdown", "filepath": str(filepath)}

    # Parse frontmatter between --- markers
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if match:
        for line in match.group(1).splitlines():
            if ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip().lower()] = val.strip()
        meta["prompt"] = match.group(2).strip()
    else:
        meta["prompt"] = text.strip()

    # slug = filename stem, always stable for API lookups
    meta["slug"] = filepath.stem
    meta.setdefault("schedule", "every 6h")
    meta.setdefault("description", "")
    meta.setdefault("enabled", "true")
    meta.setdefault("output", "local")
    meta.setdefault("data", "timeline, apps")  # default data sections
    meta.setdefault("model_requirement", "0")  # min context tokens needed
    meta["enabled"] = meta["enabled"].lower() in ("true", "yes", "1")
    # Parse data sections into a set
    meta["_data_sections"] = {s.strip().lower() for s in meta["data"].split(",")}
    try:
        meta["_model_req"] = int(meta["model_requirement"])
    except (ValueError, TypeError):
        meta["_model_req"] = 0
    return meta


def _parse_py_frontmatter(filepath: Path) -> dict:
    """Parse metadata from a Python plugin's docstring."""
    text = filepath.read_text(encoding="utf-8")
    meta = {"name": filepath.stem, "type": "python", "filepath": str(filepath)}

    # Extract triple-quoted docstring
    match = re.match(r'^"""(.*?)"""', text, re.DOTALL)
    if not match:
        match = re.match(r"^'''(.*?)'''", text, re.DOTALL)
    
    if match:
        for line in match.group(1).strip().splitlines():
            if ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip().lower()] = val.strip()

    # slug = filename stem, always stable for API lookups
    meta["slug"] = filepath.stem
    meta.setdefault("schedule", "every 1h")
    meta.setdefault("description", "")
    meta.setdefault("enabled", "true")
    meta.setdefault("output", "local")
    meta.setdefault("data", "")  # Python plugins use SDK, not data injection
    meta.setdefault("model_requirement", "0")
    meta["enabled"] = meta["enabled"].lower() in ("true", "yes", "1")
    # Parse data sections into a set
    meta["_data_sections"] = {s.strip().lower() for s in meta["data"].split(",") if s.strip()}
    try:
        meta["_model_req"] = int(meta["model_requirement"])
    except (ValueError, TypeError):
        meta["_model_req"] = 0
    return meta


def discover_agents() -> list:
    """Scan agents directory and return list of agent metadata dicts."""
    agents_dir = get_agents_dir()
    agents = []

    for f in sorted(agents_dir.iterdir()):
        try:
            if f.suffix == ".md" and not f.name.startswith("_"):
                agents.append(_parse_md_frontmatter(f))
            elif f.suffix == ".py" and not f.name.startswith("_"):
                agents.append(_parse_py_frontmatter(f))
        except Exception as e:
            logger.warning(f"Error parsing {f.name}: {e}")

    return agents


# ── Schedule Parsing ─────────────────────────────────────────────────

def _parse_interval_seconds(schedule: str) -> int:
    """Parse schedule string to seconds. Supports: every 30m, every 1h, every 6h, daily."""
    schedule = schedule.strip().lower()

    m = re.match(r"every\s+(\d+)\s*m(?:in)?", schedule)
    if m:
        return int(m.group(1)) * 60

    m = re.match(r"every\s+(\d+)\s*h(?:our)?", schedule)
    if m:
        return int(m.group(1)) * 3600

    if "daily" in schedule:
        return 86400

    # Default: every 6 hours
    return 21600


# ── Execution ────────────────────────────────────────────────────────

def _run_markdown_agent(agent: dict) -> str:
    """Execute a markdown agent by calling Gemma with injected screen data.

    Data injection is controlled by the agent's `data:` frontmatter field
    and adapts to the model's context_window setting.
    """
    from screenmind.engine import llm_client
    from collections import Counter

    # Determine which data sections the agent wants
    requested = agent.get("_data_sections", {"timeline", "apps"})
    model_req = agent.get("_model_req", 0)

    # Adaptive budget based on model context window
    ctx_window = settings.context_window
    available_tokens = ctx_window - 800 - 1000  # reserve for system + output
    budget = min(max(available_tokens * 4, 800), 12000)  # chars, floor 800, cap 12k

    # Get recent activities for context
    from screenmind.storage.database import Database
    db = Database()
    activities = db.get_activities_by_date(str(datetime.now().date()), limit=200)

    # Pre-compute stats from activities
    analyzed = [a for a in activities if a.get("analyzed")]
    app_counter = Counter()
    cat_counter = Counter()
    mood_counter = Counter()
    url_counter = Counter()

    for a in analyzed:
        app_counter[a.get("app_name", "?")] += 1
        cat_counter[a.get("category", "?")] += 1
        mood = a.get("mood")
        if mood:
            mood_counter[mood] += 1
        url = a.get("active_url")
        if url:
            url_counter[url] += 1

    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    sections = []
    remaining = budget

    # --- Build sections in priority order, respecting data: selector ---

    header = f"## Today's Data ({date_str})\n\n**{len(analyzed)} screen captures analyzed**"
    sections.append(header)
    remaining -= len(header)

    # Apps section
    if "apps" in requested and remaining > 100:
        app_stats = ", ".join(f"{app}: {c}" for app, c in app_counter.most_common(8))
        cat_stats = ", ".join(f"{cat}: {c}" for cat, c in cat_counter.most_common(5))
        s = f"### App Usage\n{app_stats or 'No data'}\n\n### Activity Categories\n{cat_stats or 'No data'}"
        sections.append(s)
        remaining -= len(s)

    # URLs section
    if "urls" in requested and remaining > 100:
        max_urls = 10 if remaining > 2000 else 5 if remaining > 1000 else 3
        if url_counter:
            url_lines = []
            for url, count in url_counter.most_common(max_urls):
                # Show hostname for readability
                try:
                    from urllib.parse import urlparse
                    host = urlparse(url).hostname or url[:50]
                except Exception:
                    host = url[:50]
                url_lines.append(f"- {host} ({count}x) — {url[:80]}")
            s = "### URLs Visited\n" + "\n".join(url_lines)
            sections.append(s)
            remaining -= len(s)

    # Meetings section
    if "meetings" in requested and remaining > 100:
        try:
            meetings = db.get_meetings_by_date(str(datetime.now().date()))
            if meetings:
                mtg_lines = []
                for m in meetings[:5]:
                    start = m.get("start_time", "?")[-8:-3]  # HH:MM
                    app = m.get("app_name", "?")
                    dur = m.get("duration_minutes", 0)
                    summ = (m.get("summary") or "No summary")[:80]
                    mtg_lines.append(f"- {start} {app} ({dur}min): {summ}")
                s = "### Meetings Today\n" + "\n".join(mtg_lines)
                sections.append(s)
                remaining -= len(s)
        except Exception:
            pass

    # Done with DB — close connection
    db.close()

    # Mood section
    if "mood" in requested and remaining > 80:
        if mood_counter:
            mood_str = ", ".join(f"{m}: {c}" for m, c in mood_counter.most_common())
            s = f"### Mood Breakdown\n{mood_str}"
            sections.append(s)
            remaining -= len(s)

    # Timeline section — fills remaining budget
    if "timeline" in requested and remaining > 80:
        max_items = max(remaining // 80, 3)  # ~80 chars per line
        timeline_lines = []
        for a in analyzed[:max_items]:
            ts = a.get("timestamp", "")[-8:-3]  # HH:MM
            app = a.get("app_name", "?")
            cat = a.get("category", "?")
            summary = (a.get("summary") or "")[:60]
            url = a.get("active_url")
            url_hint = ""
            if url:
                try:
                    from urllib.parse import urlparse
                    url_hint = f" [🔗 {urlparse(url).hostname}]"
                except Exception:
                    pass
            timeline_lines.append(f"[{ts}] {app} ({cat}): {summary}{url_hint}")
        if timeline_lines:
            s = "### Activity Timeline\n" + "\n".join(timeline_lines)
            sections.append(s)

    data_payload = "\n\n".join(sections)

    # Model requirement check — add upgrade hint if needed
    upgrade_hint = ""
    if model_req > 0 and ctx_window < model_req:
        upgrade_hint = (
            f"\n\n⚠️ This agent works best with a model supporting {model_req}+ context tokens. "
            f"Your current model is configured for {ctx_window}. "
            f"Consider upgrading your model for richer results.\n"
        )
    if budget < 1500:
        upgrade_hint += (
            "\n💡 Tip: Upgrade to a model with 8k+ context for richer agent data.\n"
        )

    prompt = f"""You are an AI agent running inside ScreenMind, a screen recording + analysis tool.
The user has set up this agent with the following instructions:

{agent['prompt']}

---

{data_payload}

---

Now execute the agent's instructions based on this data. Be specific, actionable, and reference actual apps/activities."""

    try:
        result = llm_client.generate(
            prompt=prompt,
            temperature=0.3,
            max_tokens=1024,
        )
        return upgrade_hint + result if upgrade_hint else result
    except Exception as e:
        raise RuntimeError(f"Gemma call failed: {e}")


def _run_python_plugin(agent: dict) -> str:
    """Execute a Python plugin by importing and calling run()."""
    filepath = agent["filepath"]

    # Security: check if approved
    if not settings.agents_auto_run_python and filepath not in _approved_plugins:
        return "[NEEDS_APPROVAL] This Python plugin needs user confirmation to run."

    spec = importlib.util.spec_from_file_location(agent["name"], filepath)
    module = importlib.util.module_from_spec(spec)

    # Backward compat: plugins use `import screenmind_sdk` (flat name)
    import screenmind.screenmind_sdk
    sys.modules.setdefault("screenmind_sdk", screenmind.screenmind_sdk)

    spec.loader.exec_module(module)

    if not hasattr(module, "run"):
        raise RuntimeError("Plugin missing run() function")

    # Build context for the plugin — sanitized name for state isolation
    sanitized_name = re.sub(r'[^a-zA-Z0-9_-]', '', agent["name"]) or "unknown"
    context = {
        "agent_name": sanitized_name,
        "timestamp": datetime.utcnow().isoformat(),
        "data_dir": str(settings.data_path),
    }

    # Set SDK agent context before running (for state functions)
    screenmind.screenmind_sdk._set_current_agent(sanitized_name)

    try:
        result = module.run(context)
    finally:
        screenmind.screenmind_sdk._set_current_agent("unknown")

    return str(result) if result else "Plugin completed (no output)"


def run_agent(agent: dict) -> dict:
    """Run a single agent and return result dict."""
    start = time.time()
    name = agent["name"]
    agent_type = agent["type"]

    try:
        if agent_type == "markdown":
            output = _run_markdown_agent(agent)
        elif agent_type == "python":
            output = _run_python_plugin(agent)
        else:
            output = f"Unknown agent type: {agent_type}"

        duration = time.time() - start
        status = "needs_approval" if "[NEEDS_APPROVAL]" in output else "ok"
        output_dest = agent.get("output", "local")
        _log_run(name, agent_type, status, output, duration=duration, output_dest=output_dest)
        logger.info(f"{name} ({agent_type}) completed in {duration:.1f}s → {output_dest}")
        return {"status": status, "output": output, "duration": duration}

    except Exception as e:
        duration = time.time() - start
        error = traceback.format_exc()
        _log_run(name, agent_type, "error", error=str(e), duration=duration)
        logger.error(f"{name} failed: {e}")
        return {"status": "error", "output": "", "error": str(e), "duration": duration}


def approve_plugin(filepath: str):
    """Mark a Python plugin as approved to run."""
    _approved_plugins.add(filepath)


# ── Background Scheduler ─────────────────────────────────────────────

class AgentScheduler:
    """Runs agents on their configured schedules in a background thread."""

    def __init__(self):
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_run = {}  # agent name -> timestamp

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()
        logger.info("AgentScheduler started")

    def stop(self):
        self._running = False
        logger.info("AgentScheduler stopped")

    def _loop(self):
        # Wait for server to be ready
        time.sleep(10)

        while self._running:
            if not settings.agents_enabled:
                time.sleep(60)
                continue

            try:
                # Don't run agents if no model backend is available (#10)
                from screenmind.engine import model_manager
                if not model_manager.is_backend_available():
                    time.sleep(60)
                    continue

                agents = discover_agents()
                now = time.time()

                for agent in agents:
                    if not agent.get("enabled"):
                        continue

                    name = agent["name"]
                    interval = _parse_interval_seconds(agent.get("schedule", "every 6h"))
                    last = self._last_run.get(name, 0)

                    if now - last >= interval:
                        self._last_run[name] = now
                        # Run in a separate thread to not block scheduler
                        threading.Thread(
                            target=run_agent, args=(agent,), daemon=True
                        ).start()

            except Exception as e:
                logger.error(f"AgentScheduler error: {e}")

            # Check every 60 seconds
            time.sleep(60)
