"""
Agent Runner
Discovers, schedules, and executes agents from ~/.screenmind/agents/.
Supports two types:
  - .md (Markdown Agents) — Gemma-powered, no code needed
  - .py (Python Plugins) — full code, for developers
"""

import asyncio
import importlib.util
import logging
import os
import re
import sys
import threading
import time
import traceback
from collections import deque
from datetime import datetime
from pathlib import Path
from typing import Optional

from screenmind.config import settings

logger = logging.getLogger("screenmind.engine.agent_runner")


# ── Agent Log ────────────────────────────────────────────────────────
_agent_log = deque(maxlen=30)
_log_lock = threading.Lock()

# Approved Python plugins (user confirmed to run)
_approved_plugins = set()

# Persistent log file
_LOG_FILE = settings.data_path / "agents" / "run_log.json"


def _load_log():
    """Load persisted log from disk."""
    global _agent_log
    try:
        if _LOG_FILE.exists():
            import json
            data = json.loads(_LOG_FILE.read_text(encoding="utf-8"))
            _agent_log = deque(data[-30:], maxlen=30)
    except Exception:
        pass

_load_log()


def get_agent_log() -> list:
    """Return agent run log (newest first)."""
    with _log_lock:
        return list(reversed(_agent_log))


def _log_run(name: str, agent_type: str, status: str, output: str = "", error: str = "", duration: float = 0, output_dest: str = "local"):
    entry = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "name": name,
        "type": agent_type,
        "status": status,
        "output": output[:500],
        "error": error[:200],
        "duration": round(duration, 1),
    }
    with _log_lock:
        _agent_log.append(entry)
        # Persist to disk
        try:
            import json
            _LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
            _LOG_FILE.write_text(json.dumps(list(_agent_log), indent=2), encoding="utf-8")
        except Exception:
            pass

    if status != "ok" or not output:
        return

    # Parse comma-separated destinations: "local", "obsidian", "webhook", or combos
    dests = {d.strip().lower() for d in output_dest.split(",")}

    # Local file backup (always runs) — use slug for consistent path
    slug = name.lower().replace(" ", "-")
    _save_agent_output(slug, output)

    # Obsidian
    if "obsidian" in dests:
        _push_to_obsidian(name, output)

    # Webhook (Slack, Discord, custom HTTP endpoints)
    if "webhook" in dests:
        _push_to_webhook(name, output)


def _save_agent_output(name: str, output: str):
    """Save agent output to agents/output/{name}/{timestamp}.md for history."""
    try:
        out_dir = settings.data_path / "agents" / "output" / name
        out_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y-%m-%d_%H-%M")
        filepath = out_dir / f"{ts}.md"
        filepath.write_text(f"# {name} — {ts}\n\n{output}", encoding="utf-8")
    except Exception:
        pass


def _push_to_obsidian(name: str, output: str):
    """If Obsidian is enabled, write agent output to vault."""
    try:
        if not settings.obsidian_enabled or not settings.obsidian_vault_path:
            return
        vault = Path(settings.obsidian_vault_path)
        if not vault.is_dir():
            return

        # Write to {vault}/ScreenMind/Agents/{name}/{date}.md
        agent_dir = vault / "ScreenMind" / "Agents" / name
        agent_dir.mkdir(parents=True, exist_ok=True)

        date_str = datetime.now().strftime("%Y-%m-%d")
        filepath = agent_dir / f"{date_str}.md"

        content = f"# {name} — {date_str}\n\n"
        content += f"*Auto-generated by ScreenMind agent at {datetime.now().strftime('%H:%M')}*\n\n"
        content += "---\n\n"
        content += output.strip() + "\n\n"
        content += f"---\n\n#screenmind #agent #{name.lower().replace(' ', '-')}\n"

        filepath.write_text(content, encoding="utf-8")
        logger.info(f"Obsidian: Agent '{name}' output -> {filepath}")
    except Exception as e:
        logger.error(f"Obsidian: Agent push failed: {e}")


def _push_to_webhook(name: str, output: str):
    """Push agent output to configured webhook URL (Slack, Discord, etc.)."""
    try:
        if not settings.webhook_enabled or not settings.webhook_url:
            return

        import json
        import urllib.request

        url = settings.webhook_url
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Format payload — compatible with Slack/Discord incoming webhooks
        payload = {
            "text": f"*{name}* — {date_str}\n\n{output[:2000]}",
            "content": f"**{name}** — {date_str}\n\n{output[:2000]}",  # Discord
            "agent": name,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "source": "screenmind",
        }

        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url, data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        urllib.request.urlopen(req, timeout=10)
        logger.info(f"Webhook: Agent '{name}' output sent")
    except Exception as e:
        logger.error(f"Webhook: Agent push failed: {e}")


# ── Agent Discovery ──────────────────────────────────────────────────

def get_agents_dir() -> Path:
    """Get the agents directory, creating it if needed."""
    agents_dir = settings.data_path / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    return agents_dir


def _parse_md_frontmatter(filepath: Path) -> dict:
    """Parse YAML-like frontmatter from a markdown agent file."""
    text = filepath.read_text(encoding="utf-8")
    meta = {"name": filepath.stem, "type": "markdown", "filepath": str(filepath)}

    # Parse frontmatter between --- markers
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", text, re.DOTALL)
    if match:
        for line in match.group(1).splitlines():
            if ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip().lower()] = val.strip()
        meta["prompt"] = match.group(2).strip()
    else:
        meta["prompt"] = text.strip()

    # slug = filename stem, always stable for API lookups
    meta["slug"] = filepath.stem
    meta.setdefault("schedule", "every 6h")
    meta.setdefault("description", "")
    meta.setdefault("enabled", "true")
    meta.setdefault("output", "local")
    meta.setdefault("data", "timeline, apps")  # default data sections
    meta.setdefault("model_requirement", "0")  # min context tokens needed
    meta.setdefault("temperature", "0.3")  # sampling temperature for this agent
    meta.setdefault("mode", "")  # special output mode, e.g. "timesheet"
    meta["enabled"] = meta["enabled"].lower() in ("true", "yes", "1")
    # Parse data sections into a set
    meta["_data_sections"] = {s.strip().lower() for s in meta["data"].split(",")}
    try:
        meta["_model_req"] = int(meta["model_requirement"])
    except (ValueError, TypeError):
        meta["_model_req"] = 0
    try:
        meta["_temperature"] = max(0.0, min(float(meta["temperature"]), 2.0))
    except (ValueError, TypeError):
        meta["_temperature"] = 0.3
    return meta


def _parse_py_frontmatter(filepath: Path) -> dict:
    """Parse metadata from a Python plugin's docstring."""
    text = filepath.read_text(encoding="utf-8")
    meta = {"name": filepath.stem, "type": "python", "filepath": str(filepath)}

    # Extract triple-quoted docstring
    match = re.match(r'^"""(.*?)"""', text, re.DOTALL)
    if not match:
        match = re.match(r"^'''(.*?)'''", text, re.DOTALL)
    
    if match:
        for line in match.group(1).strip().splitlines():
            if ":" in line:
                key, _, val = line.partition(":")
                meta[key.strip().lower()] = val.strip()

    # slug = filename stem, always stable for API lookups
    meta["slug"] = filepath.stem
    meta.setdefault("schedule", "every 1h")
    meta.setdefault("description", "")
    meta.setdefault("enabled", "true")
    meta.setdefault("output", "local")
    meta.setdefault("data", "")  # Python plugins use SDK, not data injection
    meta.setdefault("model_requirement", "0")
    meta["enabled"] = meta["enabled"].lower() in ("true", "yes", "1")
    # Parse data sections into a set
    meta["_data_sections"] = {s.strip().lower() for s in meta["data"].split(",") if s.strip()}
    try:
        meta["_model_req"] = int(meta["model_requirement"])
    except (ValueError, TypeError):
        meta["_model_req"] = 0
    return meta


def discover_agents() -> list:
    """Scan agents directory and return list of agent metadata dicts."""
    agents_dir = get_agents_dir()
    agents = []

    for f in sorted(agents_dir.iterdir()):
        try:
            if f.suffix == ".md" and not f.name.startswith("_"):
                agents.append(_parse_md_frontmatter(f))
            elif f.suffix == ".py" and not f.name.startswith("_"):
                agents.append(_parse_py_frontmatter(f))
        except Exception as e:
            logger.warning(f"Error parsing {f.name}: {e}")

    return agents


# ── Schedule Parsing ─────────────────────────────────────────────────

def _parse_interval_seconds(schedule: str) -> int:
    """Parse schedule string to seconds. Supports: every 30m, every 1h, every 6h, daily."""
    schedule = schedule.strip().lower()

    m = re.match(r"every\s+(\d+)\s*m(?:in)?", schedule)
    if m:
        return int(m.group(1)) * 60

    m = re.match(r"every\s+(\d+)\s*h(?:our)?", schedule)
    if m:
        return int(m.group(1)) * 3600

    if "daily" in schedule:
        return 86400

    # Default: every 6 hours
    return 21600


# ── Execution ────────────────────────────────────────────────────────

def _hhmm(timestamp: str) -> str:
    """Extract HH:MM from an ISO timestamp. Handles both SQLite default
    ('2026-08-14 10:30:06') and Python isoformat with microseconds
    ('2026-08-14T10:30:06.985914')."""
    try:
        from datetime import datetime as _dt
        return _dt.fromisoformat(str(timestamp)).strftime("%H:%M")
    except (ValueError, TypeError):
        return "??:??"


# ── Timesheet Mode ───────────────────────────────────────────────────
# Code owns the output format (grouping, sorting, subtotals, ticket
# numbers, times, customers); the LLM only contributes per-session
# subjects and justifications. Small local models drift on strict
# copy-and-edit tasks, so anything format-critical stays deterministic.

_TICKET_NUM_RE = re.compile(r"ticket\s+(\d{4,6})", re.I)
_NOISE_DOMAINS = {
    "gmail", "outlook", "google", "microsoft", "gits", "screenmind",
    "yahoo", "hotmail", "office", "office365", "live", "icloud",
    "proton", "localhost", "example", "aka", "hubspot", "hubspotlinks",
    "threatlocker", "splunk", "eurodns", "learn",
    # OCR manglings of "gits" seen in captures
    "gils", "glts", "g1ts",
}
# Window titles that are never billable work
_NOISE_TITLE_RE = re.compile(
    r"lock\s*screen|screenmind|program manager|"
    r"mercedes|mobile\.de|autoscout|youtube|netflix|amazon",
    re.I,
)
_DOMAIN_IN_TITLE_RE = re.compile(
    r"\b([a-z][a-z0-9-]{2,30})\.(?:com|net|org|lu|fr|de|io)\b", re.I
)
_CAPS_NAME_RE = re.compile(r"\b([A-Z][A-Z][A-Z0-9-]{2,25})\b")
_CAPS_NOISE = {
    "GITS", "PSF", "SOC", "O365", "PDF", "HTML", "URL", "HTTP", "HTTPS",
    "SSL", "DNS", "VPN", "USB", "CSV", "XML", "JSON", "API", "IT", "AD",
    "FSLOGIX", "CIPP", "AZURE", "POWERSHELL", "INCIDENT", "REPORT",
    "READ", "ONLY", "WORD", "EXCEL", "OUTLOOK", "TEAMS", "CHROME",
    "GOOGLE", "MICROSOFT", "WINDOWS", "DESKTOP", "VIEWER", "BASTION",
    "MGT", "MANAGEMENT", "SHAREPOINT", "PERMISSIONS", "VBILOKOBYLSKYI",
    "DPERILLEUX", "PS1", "DOCX", "XLSX", "PPTX", "PSM1", "GLOBAL",
    "SERVICES", "STANDARDS", "HIGH", "SECURITY", "DRIFT", "CLONE",
    "REMEDI", "ERROR", "CLARIFICATION", "FILTER", "BOOK1", "V2", "V1",
    "XA", "DG5017", "ELEA", "WORK", "REVIEW", "MY", "TICKETS", "HELPDESK",
    "CALENDAR", "CLIENTS", "ASSETS", "DASHBOARD", "GROUP", "XVANTAGE",
    # internal infrastructure / session hosts, not customers
    "GITSMGMT", "DG5017", "BASTION", "XA", "FSLOGIX", "MGT",
}


def _customer_from_text(text: str) -> str:
    """Best-effort customer name from screen text. Email domains are the
    strongest signal; OCR-mangled 'name com' patterns are the fallback.
    Returns '' when nothing identifies a customer."""
    email_domains = []
    for d in re.findall(r"[\w.-]+@([\w-]+(?:\.[\w-]+)+)", text):
        email_domains.append(d.lower().split(".")[0])
    for d in email_domains:
        if not any(n in d for n in _NOISE_DOMAINS) and len(d) >= 3:
            return d
    for d in re.findall(
        r"\b([a-z][a-z0-9-]{2,30})[_ ](?:com|net|org|lu|fr|de|io)\b",
        text.lower(),
    ):
        if not any(n in d for n in _NOISE_DOMAINS) and len(d) >= 3:
            return d
    return ""


def _parse_iso(v):
    try:
        return datetime.fromisoformat(str(v))
    except (ValueError, TypeError):
        return None


def _span_minutes(ts_list, interval: int) -> int:
    """Time on task from capture timestamps: first capture counts one
    interval, each gap counts up to 2x interval (same method as the
    daily summary). Rounded to 5 minutes, minimum 5."""
    if not ts_list:
        return 0
    total = float(interval)
    for prev, cur in zip(ts_list, ts_list[1:]):
        gap = (cur - prev).total_seconds()
        if gap > 0:
            total += min(gap, 2 * interval)
    return max(5, int(round(total / 60.0 / 5.0)) * 5)


def _fmt_dur(minutes: int) -> str:
    return f"{minutes} min" if minutes < 60 else f"{minutes // 60}:{minutes % 60:02d} h"


def _lev(a: str, b: str) -> int:
    """Small Levenshtein for typo-tolerant customer merging."""
    if len(a) < len(b):
        a, b = b, a
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1]


def _normalize_title(title: str) -> str:
    """Reduce a window title to a stable grouping key: strip app suffixes,
    file extensions, and collapse whitespace."""
    t = title.strip()
    # App suffixes like " - Google Chrome", " - Word", " - Outlook"
    t = re.sub(r"\s+[-–]\s+(Google Chrome|Mozilla Firefox|Word|Excel|Outlook|"
               r"PowerPoint|Visual Studio Code|Notepad|Microsoft Teams).*$", "", t, flags=re.I)
    # File extensions
    t = re.sub(r"\.(docx?|xlsx?|pptx?|ps1|psm1|pdf|txt|csv|md)\b", "", t, flags=re.I)
    return " ".join(t.split())


def _customer_from_title(title: str) -> str:
    """Customer from a window title: domain (users - engelwoodgroup.com) or
    an ALL-CAPS company token (INCIDENT REPORT - ATDOMCO - O365 ...)."""
    for m in _DOMAIN_IN_TITLE_RE.finditer(title):
        name = m.group(1).lower()
        if name not in _NOISE_DOMAINS and len(name) >= 3:
            return name
    for m in _CAPS_NAME_RE.finditer(title):
        tok = m.group(1)
        if tok.isdigit():
            continue
        # Split hyphenated tokens: GITSMGMT-XA is infra, not a customer
        parts = tok.split("-")
        if all(p in _CAPS_NOISE or len(p) < 2 for p in parts):
            continue
        if tok in _CAPS_NOISE:
            continue
        return tok.lower()
    return ""


def _preset_subject(title: str, app: str) -> str:
    """Deterministic subject for well-known window patterns; '' otherwise."""
    app_low = (app or "").lower()
    t = title
    if "inbox" in t.lower() or "sent items" in t.lower():
        return "Email (inbox/sent)"
    m = re.search(r"\|\s*([^|]+?)\s*channel\s*\|", t, re.I)
    if m:
        return f"Teams: {m.group(1).strip()}"
    # Remote-desktop windows (Citrix/Desktop Viewer): the hostname in the
    # title is NOT a task. No preset here — the LLM classifies from OCR,
    # and unclassifiable sessions are folded into one "Remote
    # administration" line in _run_timesheet_mode.
    if re.search(r"\belea\b", t, re.I):
        return "ELEA time/management"
    if re.search(r"\bwork\s*review\b", t, re.I):
        return "Work review"
    return ""

_EDITOR_SUFFIX_RE = re.compile(
    r"\s+[-–]\s+(?:Visual Studio Code|Word|Excel|PowerPoint|Notepad\+\+|"
    r"PowerShell ISE|ISE|Sublime Text|Notepad|Read-Only)\s*$", re.I,
)
_GENERIC_SEGMENTS = {
    "users", "inbox", "sent items", "home", "dashboard", "new tab",
    "untitled", "welcome", "chat", "calendar",
}


def _fallback_subject(title: str) -> str:
    """Last-resort subject from the window title itself: the active
    document/file segment. 'SplunkInstall.ps1 - Sharepoint Permissions -
    Visual Studio Code' -> 'SplunkInstall' (the open file is the task,
    not the whole composite title)."""
    t = title.strip()
    for _ in range(3):  # peel trailing app/state suffixes
        t2 = _EDITOR_SUFFIX_RE.sub("", t)
        if t2 == t:
            break
        t = t2
    for seg in re.split(r"\s+[-–]\s+", t):
        seg = seg.strip()
        if len(seg) < 3 or seg.lower() in _GENERIC_SEGMENTS:
            continue
        seg = re.sub(
            r"\.(docx?|xlsx?|pptx?|ps1|psm1|pdf|txt|csv|md|py|js|ts)\b",
            "", seg, flags=re.I,
        )
        seg = " ".join(seg.split())
        if len(seg) >= 3:
            return seg[:60]
    return ""


def _aggregate_timesheet(analyzed: list, interval: int):
    """Split the day's captures into helpdesk-ticket work (window title
    'Ticket NNNNN') and other work grouped by normalized window title.

    Returns (tickets, other):
      tickets: [{"num", "minutes", "customer", "texts": [..]}]
      other:   [{"title", "minutes", "customer", "subject", "texts": [..]}]
    """
    chrono = []
    for a in analyzed:
        ts = _parse_iso(a.get("timestamp"))
        if ts:
            chrono.append((ts, a))
    chrono.sort(key=lambda x: x[0])

    tickets = {}
    other = {}
    for ts, a in chrono:
        title = a.get("window_title") or ""
        m = _TICKET_NUM_RE.search(title)
        if m:
            num = m.group(1)
            entry = tickets.setdefault(num, {"times": [], "texts": [], "customer": "", "_seen": set()})
            entry["times"].append(ts)
            text = (a.get("organized_text") or a.get("ocr_text") or "").strip()
            if text:
                key = text[:80]
                if key not in entry["_seen"] and len(entry["texts"]) < 10:
                    entry["_seen"].add(key)
                    entry["texts"].append(" ".join(text.split())[:600])
                if not entry["customer"]:
                    entry["customer"] = _customer_from_text(text)
        else:
            if not title.strip() or _NOISE_TITLE_RE.search(title):
                continue
            key = _normalize_title(title)[:80]
            app_low = (a.get("app_name") or "").lower()
            entry = other.setdefault(
                key,
                {"times": [], "title": key, "app": a.get("app_name") or "?",
                 "customer": "", "texts": [], "_seen": set(),
                 "remote": "desktop viewer" in key.lower() or "citrix" in app_low},
            )
            entry["times"].append(ts)
            if not entry["customer"]:
                entry["customer"] = _customer_from_title(title)
            text = (a.get("organized_text") or a.get("ocr_text") or "").strip()
            if text:
                tkey = text[:80]
                if tkey not in entry["_seen"] and len(entry["texts"]) < 10:
                    entry["_seen"].add(tkey)
                    entry["texts"].append(" ".join(text.split())[:600])

    ticket_rows = []
    for num, entry in tickets.items():
        ticket_rows.append({
            "num": num,
            "minutes": _span_minutes(entry["times"], interval),
            "customer": (entry["customer"] or "—").upper().replace("-", " "),
            "texts": entry["texts"],
        })
    ticket_rows.sort(key=lambda t: t["minutes"], reverse=True)

    other_rows = []
    for entry in other.values():
        minutes = _span_minutes(entry["times"], interval)
        if minutes < 5:
            continue
        subject = _preset_subject(entry["title"], entry["app"])
        other_rows.append({
            "title": entry["title"],
            "minutes": minutes,
            "customer": (entry["customer"] or "—").upper().replace("-", " "),
            "subject": subject,
            "texts": entry["texts"],
        })
    other_rows.sort(key=lambda r: r["minutes"], reverse=True)

    return ticket_rows, other_rows[:15]


def _run_timesheet_mode(agent: dict, date: str | None = None) -> str:
    """Timesheet agent: deterministic aggregation (ticket numbers, times,
    grouping, sorting, subtotals) + one LLM call that classifies every
    session — customer, subject, and a screen-evidence justification —
    from its real screen text.

    The model's context window is filled with screen text, budgeted
    proportionally to time spent per session. Small local models drift on
    format, so anything format-critical stays in code.

    `date` (YYYY-MM-DD) overrides "today" for backfill runs."""
    from screenmind.engine import llm_client
    from screenmind.storage.database import Database

    target_date = date or str(datetime.now().date())
    db = Database()
    try:
        activities = db.get_activities_by_date(target_date, limit=2000)
    finally:
        db.close()
    analyzed = [a for a in activities if a.get("analyzed")]
    tickets, other = _aggregate_timesheet(analyzed, settings.capture_interval)
    if not tickets and not other:
        return f"No ticket activity found for {target_date}."

    # ── Classification digest: fill the context window with screen text ──
    sessions = []
    for t in tickets:
        sessions.append({
            "id": f"T{t['num']}", "kind": "ticket",
            "label": f"helpdesk ticket {t['num']}",
            "minutes": t["minutes"], "texts": t["texts"], "row": t,
        })
    for i, o in enumerate(other, 1):
        sessions.append({
            "id": f"O{i}", "kind": "other",
            "label": f"window: {o['title']}",
            "minutes": o["minutes"], "texts": o["texts"], "row": o,
        })

    window = llm_client.text_model_window() or settings.context_window
    # Reserve framing (~800 tokens) + output (~45 tokens per session + margin)
    out_tokens = max(512, len(sessions) * 45 + 128)
    budget_chars = max(2000, (window - 800 - out_tokens) * 4)
    total_min = sum(s["minutes"] for s in sessions) or 1

    blocks = []
    used = 0
    for s in sessions:
        share = max(300, int(budget_chars * s["minutes"] / total_min))
        body = "\n".join(s["texts"])[:share] or "(no screen text captured)"
        header = f"== {s['id']} | {s['label']} | {_fmt_dur(s['minutes'])} =="
        if blocks and used + len(header) + len(body) > budget_chars:
            body = "(text omitted — budget exhausted)"
        blocks.append(f"{header}\n{body}")
        used += len(header) + len(body) + 1

    prompt = (
        f"A user worked on the tasks below on {target_date}. Each block shows "
        "what was on their screen during that task (OCR text, may be garbled).\n"
        "For EACH block write exactly one line:\n"
        "ID | CUSTOMER | SUBJECT | JUSTIFICATION\n"
        "- ID: the block id (T99177, O1, ...)\n"
        "- CUSTOMER: the client/company this work was for — infer from email "
        'domains, company names, document names in the text; "—" if unknown\n'
        '- SUBJECT: what was done, max 8 words; "—" if unclear\n'
        "- JUSTIFICATION: one short sentence (max 15 words) naming the concrete "
        "on-screen evidence for this work — the document, error, request, email "
        'thread or system visible in the text; "—" if nothing specific is visible\n'
        "- Titles like 'HOSTNAME - Desktop Viewer' are remote-desktop "
        "sessions, NOT tasks — say what was done inside, from the screen text\n"
        "No other text.\n\n" + "\n\n".join(blocks)
    )

    classified = {}  # id -> (customer, subject, justification)
    try:
        raw = llm_client.generate(
            prompt=prompt,
            temperature=agent.get("_temperature", 0.1),
            max_tokens=out_tokens,
        )
        known = {s["id"] for s in sessions}
        for line in raw.splitlines():
            m = re.match(
                r"\s*(T\d{4,6}|O\d+)\s*\|\s*([^|]*)\|\s*([^|]*)\|?\s*(.*)$", line
            )
            if m and m.group(1) in known:
                # 3-field answers (no justification) still parse: group(4) == ""
                classified[m.group(1)] = (
                    m.group(2).strip()[:40],
                    m.group(3).strip(),
                    m.group(4).strip(),
                )
    except Exception:
        pass  # fall back to code-only classification below

    # ── Merge: code-derived facts win; the model fills the gaps ──
    def _clean(subj):
        subj = (subj or "").strip().strip("|").strip()
        if not subj or subj.startswith("—") or subj.lower() in (
            "unknown", "n/a", "no inferable subject",
        ):
            return ""
        return subj[:60]

    def _clean_just(j):
        """Justification line: drop placeholders, cap length."""
        j = (j or "").strip().strip("|").strip()
        if not j or j.startswith("—") or j.lower() in ("unknown", "n/a"):
            return ""
        return j[:140]

    groups = {}
    remote_fb = 0  # minutes of remote sessions the LLM couldn't classify
    for s in sessions:
        row = s["row"]
        m_cust, m_subj, m_just = classified.get(s["id"], ("", "", ""))
        m_cust = (m_cust or "").upper().replace("-", " ").strip()
        if m_cust in ("", "—", "UNKNOWN"):
            m_cust = ""
        # Reject model-suggested "customers" that are just infra/app tokens
        if m_cust and all(
            tok in _CAPS_NOISE or len(tok) < 2 for tok in m_cust.split()
        ):
            m_cust = ""
        just = _clean_just(m_just)
        if s["kind"] == "ticket":
            customer = row["customer"] if row["customer"] != "—" else (m_cust or "—")
            subject = _clean(m_subj) or "—"
            ticket_label = f"Ticket {row['num']}"
        else:
            customer = row["customer"] if row["customer"] != "—" else (m_cust or "—")
            if row.get("remote") and not _clean(m_subj):
                # Hostname of a remote session is not a task; if the screen
                # text doesn't reveal the work, fold into one summary line.
                remote_fb += row["minutes"]
                continue
            preset = row["subject"] or ""
            subject = (
                preset if preset and preset != "—"
                else _clean(m_subj) or _fallback_subject(row["title"]) or "—"
            )
            ticket_label = "—"
        groups.setdefault(customer, []).append(
            (ticket_label, subject, row["minutes"], just))

    if remote_fb:
        groups.setdefault("—", []).append(
            ("—", "Remote administration (Citrix)", remote_fb, ""))

    # Merge near-duplicate customers ("OMEA ADVISORS" vs "OMEA ADVISORS SARL")
    merged = {}
    for cust, rows in groups.items():
        target = cust
        old_key = None
        for existing in list(merged.keys()):
            if cust == "—" or existing == "—":
                continue
            near = cust.startswith(existing) or existing.startswith(cust)
            if not near:
                # OCR typos: ENGELWVOODGROUP vs ENGELWOODGROUP
                d = _lev(cust, existing)
                near = (d <= 1 and min(len(cust), len(existing)) >= 6) or (
                    d <= 2 and min(len(cust), len(existing)) >= 10
                )
            if near:
                target = cust if len(cust) < len(existing) else existing
                old_key = existing if existing != target else None
                break
        merged.setdefault(target, []).extend(rows)
        if old_key and old_key in merged and old_key != target:
            merged[target].extend(merged.pop(old_key))
    groups = merged

    ordered = sorted(
        groups.items(),
        key=lambda kv: (kv[0] == "—", -sum(r[2] for r in kv[1])),
    )
    out = []
    for cust, rows in ordered:
        out.append(cust)
        for ticket, subj, minutes, just in sorted(
            rows, key=lambda r: r[2], reverse=True
        ):
            out.append(f"{ticket} | {cust} | {subj} | {_fmt_dur(minutes)}")
            if just:
                out.append(f"    because: {just}")
        out.append(f"Subtotal: {_fmt_dur(sum(r[2] for r in rows))}")
        out.append("")
    return "\n".join(out).rstrip()


def _run_markdown_agent(agent: dict) -> str:
    """Execute a markdown agent by calling Gemma with injected screen data.

    Data injection is controlled by the agent's `data:` frontmatter field
    and adapts to the model's context_window setting.
    """
    from screenmind.engine import llm_client
    from collections import Counter

    # Special output modes own their entire pipeline (data + format).
    if agent.get("mode", "").strip().lower() == "timesheet":
        return _run_timesheet_mode(agent, date=agent.get("_run_date"))

    # Determine which data sections the agent wants
    requested = agent.get("_data_sections", {"timeline", "apps"})
    model_req = agent.get("_model_req", 0)

    # Adaptive budget based on model context window
    ctx_window = settings.context_window
    available_tokens = ctx_window - 800 - 2048  # reserve for system + output
    # OCR agents need many captures to cover a full day — let them use the
    # whole token-derived budget; summary-style agents stay capped at 12k.
    chars = max(available_tokens * 4, 800)
    budget = chars if "ocr" in requested else min(chars, 12000)

    # Get recent activities for context
    from screenmind.storage.database import Database
    db = Database()
    activities = db.get_activities_by_date(str(datetime.now().date()), limit=2000)

    # Pre-compute stats from activities
    analyzed = [a for a in activities if a.get("analyzed")]
    app_counter = Counter()
    cat_counter = Counter()
    mood_counter = Counter()
    url_counter = Counter()

    for a in analyzed:
        app_counter[a.get("app_name", "?")] += 1
        cat_counter[a.get("category", "?")] += 1
        mood = a.get("mood")
        if mood:
            mood_counter[mood] += 1
        url = a.get("active_url")
        if url:
            url_counter[url] += 1

    date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    sections = []
    remaining = budget

    # --- Build sections in priority order, respecting data: selector ---

    header = f"## Today's Data ({date_str})\n\n**{len(analyzed)} screen captures analyzed**"
    sections.append(header)
    remaining -= len(header)

    # Apps section
    if "apps" in requested and remaining > 100:
        app_stats = ", ".join(f"{app}: {c}" for app, c in app_counter.most_common(8))
        cat_stats = ", ".join(f"{cat}: {c}" for cat, c in cat_counter.most_common(5))
        s = f"### App Usage\n{app_stats or 'No data'}\n\n### Activity Categories\n{cat_stats or 'No data'}"
        sections.append(s)
        remaining -= len(s)

    # URLs section
    if "urls" in requested and remaining > 100:
        max_urls = 10 if remaining > 2000 else 5 if remaining > 1000 else 3
        if url_counter:
            url_lines = []
            for url, count in url_counter.most_common(max_urls):
                # Show hostname for readability
                try:
                    from urllib.parse import urlparse
                    host = urlparse(url).hostname or url[:50]
                except Exception:
                    host = url[:50]
                url_lines.append(f"- {host} ({count}x) — {url[:80]}")
            s = "### URLs Visited\n" + "\n".join(url_lines)
            sections.append(s)
            remaining -= len(s)

    # Meetings section
    if "meetings" in requested and remaining > 100:
        try:
            meetings = db.get_meetings_by_date(str(datetime.now().date()))
            if meetings:
                mtg_lines = []
                for m in meetings[:5]:
                    start = m.get("start_time", "?")[-8:-3]  # HH:MM
                    app = m.get("app_name", "?")
                    dur = m.get("duration_minutes", 0)
                    summ = (m.get("summary") or "No summary")[:80]
                    mtg_lines.append(f"- {start} {app} ({dur}min): {summ}")
                s = "### Meetings Today\n" + "\n".join(mtg_lines)
                sections.append(s)
                remaining -= len(s)
        except Exception:
            pass

    # Done with DB — close connection
    db.close()

    # Mood section
    if "mood" in requested and remaining > 80:
        if mood_counter:
            mood_str = ", ".join(f"{m}: {c}" for m, c in mood_counter.most_common())
            s = f"### Mood Breakdown\n{mood_str}"
            sections.append(s)
            remaining -= len(s)
    # Screen-activity section for timesheet-style agents.
    # Ticket work is aggregated per ticket number (all captures for a ticket
    # merged across the day, with total time + a screen-text sample for
    # customer/subject context). Everything else is compressed into a short
    # per-app summary. Keeps the payload small and free of repeated lines,
    # which small local models handle much better than raw capture lists.
    if "ocr" in requested and remaining > 100:
        interval = settings.capture_interval
        ticket_num_re = re.compile(r"ticket\s+(\d{4,6})", re.I)
        # Domain fragments that never identify a customer (free mail, vendors, OCR noise)
        _noise_domains = {
            "gmail", "outlook", "google", "microsoft", "gits", "screenmind",
            "yahoo", "hotmail", "office", "office365", "live", "icloud",
            "proton", "localhost", "example",
        }

        def _customer_from_text(text):
            """Best-effort customer name from screen text: email domains and
            OCR-mangled 'name com' patterns. Returns '' when nothing found."""
            found = []
            for d in re.findall(r"[\w.-]+@([\w-]+(?:\.[\w-]+)+)", text):
                found.append(d.lower().split(".")[0])
            for d in re.findall(
                r"\b([a-z][a-z0-9-]{2,30})[_ ](?:com|net|org|lu|fr|de|io)\b",
                text.lower(),
            ):
                found.append(d)
            for d in found:
                if not any(n in d for n in _noise_domains) and len(d) >= 3:
                    return d
            return ""

        def _parse_iso(v):
            try:
                return datetime.fromisoformat(str(v))
            except (ValueError, TypeError):
                return None

        def _span_minutes(ts_list):
            if not ts_list:
                return 0
            total = float(interval)
            for prev, cur in zip(ts_list, ts_list[1:]):
                gap = (cur - prev).total_seconds()
                if gap > 0:
                    total += min(gap, 2 * interval)
            return max(1, int(round(total / 60.0)))

        chrono = []
        for a in analyzed:
            ts = _parse_iso(a.get("timestamp"))
            if ts:
                chrono.append((ts, a))
        chrono.sort(key=lambda x: x[0])  # oldest first

        tickets = {}   # ticket number -> {"times": [], "texts": [], "customer": ""}
        other_app = {} # app_name -> [datetime]
        for ts, a in chrono:
            title = a.get("window_title") or ""
            m = ticket_num_re.search(title)
            if m:
                num = m.group(1)
                entry = tickets.setdefault(num, {"times": [], "texts": [], "customer": ""})
                entry["times"].append(ts)
                text = (a.get("organized_text") or a.get("ocr_text") or "").strip()
                if text and len(entry["texts"]) < 3:
                    entry["texts"].append(" ".join(text.split())[:160])
                if text and not entry["customer"]:
                    entry["customer"] = _customer_from_text(text)
            else:
                app = a.get("app_name") or "?"
                app = re.sub(r"[^a-z0-9]", "", app.lower()) or "?"
                other_app.setdefault(app, []).append(ts)

        def _fmt_dur(minutes):
            return f"{minutes} min" if minutes < 60 else f"{minutes // 60}:{minutes % 60:02d} h"

        lines = []
        if tickets:
            # Pre-grouped timesheet template: customer headers, per-ticket
            # lines sorted longest-first, and subtotals are all computed
            # here — the model only fills the SUBJECT blanks.
            lines.append("TIMESHEET TEMPLATE — fill each ??? with a short subject:")
            groups = {}
            for num, entry in tickets.items():
                cust = (entry["customer"] or "—").upper()
                minutes = max(5, int(round(_span_minutes(entry["times"]) / 5.0)) * 5)
                groups.setdefault(cust, []).append((num, minutes, entry))
            for cust, rows in sorted(
                groups.items(),
                key=lambda kv: sum(m for _, m, _ in kv[1]),
                reverse=True,
            ):
                lines.append(cust)
                for num, minutes, entry in sorted(rows, key=lambda r: r[1], reverse=True):
                    lines.append(f"Ticket {num} | {cust} | ??? | {_fmt_dur(minutes)}")
                    if entry["texts"]:
                        lines.append(f"    screen text: {entry['texts'][0]}")
                lines.append(f"Subtotal: {_fmt_dur(sum(m for _, m, _ in rows))}")
                lines.append("")

        if other_app:
            lines.append("Other activity (no helpdesk ticket):")
            for app, times in sorted(other_app.items(), key=lambda kv: _span_minutes(kv[1]), reverse=True)[:12]:
                minutes = _span_minutes(times)
                dur = f"{minutes} min" if minutes < 60 else f"{minutes // 60}:{minutes % 60:02d} h"
                lines.append(f"- {app}: {times[0].strftime('%H:%M')}-{times[-1].strftime('%H:%M')}, ~{dur}")

        if lines:
            s = (
                f"### Screen Activity Summary ({len(tickets)} helpdesk tickets)\n"
                f"(time estimated from capture spans; captures every ~{interval}s)\n"
                + "\n".join(lines)
            )
            sections.append(s)

    # Timeline section — fills remaining budget
    if "timeline" in requested and remaining > 80:
        max_items = max(remaining // 80, 3)  # ~80 chars per line
        timeline_lines = []
        for a in analyzed[:max_items]:
            ts = _hhmm(a.get("timestamp", ""))
            app = a.get("app_name", "?")
            cat = a.get("category", "?")
            summary = (a.get("summary") or "")[:60]
            url = a.get("active_url")
            url_hint = ""
            if url:
                try:
                    from urllib.parse import urlparse
                    url_hint = f" [🔗 {urlparse(url).hostname}]"
                except Exception:
                    pass
            timeline_lines.append(f"[{ts}] {app} ({cat}): {summary}{url_hint}")
        if timeline_lines:
            s = "### Activity Timeline\n" + "\n".join(timeline_lines)
            sections.append(s)

    data_payload = "\n\n".join(sections)

    # Model requirement check — add upgrade hint if needed
    upgrade_hint = ""
    if model_req > 0 and ctx_window < model_req:
        upgrade_hint = (
            f"\n\n⚠️ This agent works best with a model supporting {model_req}+ context tokens. "
            f"Your current model is configured for {ctx_window}. "
            f"Consider upgrading your model for richer results.\n"
        )
    if budget < 1500:
        upgrade_hint += (
            "\n💡 Tip: Upgrade to a model with 8k+ context for richer agent data.\n"
        )

    prompt = f"""You are an AI agent running inside ScreenMind, a screen recording + analysis tool.
The user has set up this agent with the following instructions:

{agent['prompt']}

---

{data_payload}

---

Now execute the agent's instructions based on this data. Follow the agent's output format exactly."""

    try:
        result = llm_client.generate(
            prompt=prompt,
            temperature=agent.get("_temperature", 0.3),
            max_tokens=2048,
        )
        return upgrade_hint + result if upgrade_hint else result
    except Exception as e:
        raise RuntimeError(f"Gemma call failed: {e}")


def _run_python_plugin(agent: dict, date: str | None = None) -> str:
    """Execute a Python plugin by importing and calling run().
    `date` (YYYY-MM-DD) is forwarded to the plugin via context["date"]
    for backfill runs; plugins that don't support it ignore it."""
    filepath = agent["filepath"]

    # Security: check if approved
    if not settings.agents_auto_run_python and filepath not in _approved_plugins:
        return "[NEEDS_APPROVAL] This Python plugin needs user confirmation to run."

    spec = importlib.util.spec_from_file_location(agent["name"], filepath)
    module = importlib.util.module_from_spec(spec)

    # Backward compat: plugins use `import screenmind_sdk` (flat name)
    import screenmind.screenmind_sdk
    sys.modules.setdefault("screenmind_sdk", screenmind.screenmind_sdk)

    spec.loader.exec_module(module)

    if not hasattr(module, "run"):
        raise RuntimeError("Plugin missing run() function")

    # Build context for the plugin — sanitized name for state isolation
    sanitized_name = re.sub(r'[^a-zA-Z0-9_-]', '', agent["name"]) or "unknown"
    context = {
        "agent_name": sanitized_name,
        "timestamp": datetime.utcnow().isoformat(),
        "data_dir": str(settings.data_path),
    }
    if date:
        context["date"] = date

    # Set SDK agent context before running (for state functions)
    screenmind.screenmind_sdk._set_current_agent(sanitized_name)

    try:
        result = module.run(context)
    finally:
        screenmind.screenmind_sdk._set_current_agent("unknown")

    return str(result) if result else "Plugin completed (no output)"


def run_agent(agent: dict, date: str | None = None) -> dict:
    """Run a single agent and return result dict. `date` (YYYY-MM-DD)
    overrides "today" for modes that support it (timesheet)."""
    start = time.time()
    name = agent["name"]
    agent_type = agent["type"]

    try:
        if agent_type == "markdown":
            agent = {**agent, "_run_date": date}
            output = _run_markdown_agent(agent)
        elif agent_type == "python":
            output = _run_python_plugin(agent, date=date)
        else:
            output = f"Unknown agent type: {agent_type}"

        duration = time.time() - start
        status = "needs_approval" if "[NEEDS_APPROVAL]" in output else "ok"
        output_dest = agent.get("output", "local")
        _log_run(name, agent_type, status, output, duration=duration, output_dest=output_dest)
        logger.info(f"{name} ({agent_type}) completed in {duration:.1f}s → {output_dest}")
        return {"status": status, "output": output, "duration": duration}

    except Exception as e:
        duration = time.time() - start
        error = traceback.format_exc()
        _log_run(name, agent_type, "error", error=str(e), duration=duration)
        logger.error(f"{name} failed: {e}")
        return {"status": "error", "output": "", "error": str(e), "duration": duration}


def approve_plugin(filepath: str):
    """Mark a Python plugin as approved to run."""
    _approved_plugins.add(filepath)


# ── Background Scheduler ─────────────────────────────────────────────

class AgentScheduler:
    """Runs agents on their configured schedules in a background thread."""

    def __init__(self):
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_run = {}  # agent name -> timestamp

    def start(self):
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()
        logger.info("AgentScheduler started")

    def stop(self):
        self._running = False
        logger.info("AgentScheduler stopped")

    def _loop(self):
        # Wait for server to be ready
        time.sleep(10)

        while self._running:
            if not settings.agents_enabled:
                time.sleep(60)
                continue

            try:
                # Don't run agents if no model backend is available (#10)
                from screenmind.engine import model_manager
                if not model_manager.is_backend_available():
                    time.sleep(60)
                    continue

                agents = discover_agents()
                now = time.time()

                for agent in agents:
                    if not agent.get("enabled"):
                        continue

                    name = agent["name"]
                    interval = _parse_interval_seconds(agent.get("schedule", "every 6h"))
                    last = self._last_run.get(name, 0)

                    if now - last >= interval:
                        self._last_run[name] = now
                        # Run in a separate thread to not block scheduler
                        threading.Thread(
                            target=run_agent, args=(agent,), daemon=True
                        ).start()

            except Exception as e:
                logger.error(f"AgentScheduler error: {e}")

            # Check every 60 seconds
            time.sleep(60)
